# vim: ft=cfg
[theme]
background = "default"
primary = "#94e2d5"
secondary = "#94e2ff"
title = "#94e2ff"
playing = "#94e2ff"
playing_bg = "#94e2d5"
playing_selected = "#ebdbb2"
highlight = "#d5c4a1"
highlight_bg = "#484848"
error = "#fbf1c7"
error_bg = "#cc241d"
statusbar_progress = "#458588"
statusbar_bg = "#282828"
statusbar = "#94e2ff"
cmdline = "#d5c4a1"
cmdline_bg = "#383838"
search_match = "#94e2ff"
